---
- name: Install pip3
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present
  become: true

- name: Install required python modules
  ansible.builtin.pip:
    name:
      - requests
      - docker
      - docker-compose
  become: true

- name: Check if cadvisor compose exists
  ansible.builtin.stat:
    path: "/home/{{ ansible_user }}/cadvisor/docker-compose.yml"
  register: cadvisor_exists

- name: Stop and remove cadvisor container
  community.docker.docker_compose:
    project_src: "/home/{{ ansible_user }}/cadvisor/"
    state: absent
  when: cadvisor_exists.stat.exists

- name: Delete cadvisor service directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/cadvisor/"
    state: absent
