---
- name: "Install python requirements"
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-docker
      - python3-requests
    state: present
  become: true

- name: "Ensure cAdvisor container is running"
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    restart_policy: unless-stopped
    privileged: yes
    devices:
      - "/dev/kmsg:/dev/kmsg"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"
      - "/cgroup:/cgroup:ro"
    ports:
      - "{{ cadvisor_port }}:8080"
  become: true
