---
- name: "Stop and remove cAdvisor container"
  community.docker.docker_container:
    name: cadvisor
    state: absent
  become: true

- name: "Remove netbox service for cadvisor"
  netbox.netbox.netbox_service:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      virtual_machine: "{{ inventory_hostname }}"
      name: cAdvisor
      port: "{{ cadvisor_port }}"
      protocol: TCP
    state: absent
  delegate_to: localhost
  when:
    - netbox_url
    - netbox_token
