---
- name: Downloading and extracting node_exporter
  ansible.builtin.unarchive:
    remote_src: true
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /opt/
  become: true

- name: Create node_exporter.service file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/node_exporter.service.j2"
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'
  become: true

- name: Enables node_exporter daemon
  ansible.builtin.systemd:
    name: node_exporter
    daemon_reload: true
    enabled: true
    state: started
  become: true

- name: "Create netbox service for node_exporter"
  netbox.netbox.netbox_service:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      virtual_machine: "{{ inventory_hostname }}"
      name: node_exporter
      port: "9100"
      protocol: TCP
    state: present
  delegate_to: localhost
  when:
    - netbox_url
    - netbox_token
