---
- name: Disable node_exporter daemon
  ansible.builtin.systemd:
    name: node_exporter
    enabled: false
    state: stopped
  become: true

- name: Delete node_exporter service
  ansible.built.infile:
    state: absent
    path: /etc/systemd/system/node_exporter.service
  become: true

- name: Delete node_exporter files
  ansible.built.infile:
    state: absent
    path: "{{ uninstall_path }}"
  become: true

- name: "Remove netbox service for node_exporter"
  netbox.netbox.netbox_service:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      virtual_machine: "{{ inventory_hostname }}"
      name: node_exporter
      port: "9100"
      protocol: TCP
    state: absent
  delegate_to: localhost
  when:
    - "netbox_url is defined"
    - "netbox_token is defined"
    - "netbox_url is not none"
    - "netbox_token is not none"

