---
- name: Downloading and extracting postgresql_exporter
  ansible.builtin.unarchive:
    remote_src: true
    src: https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ postgresql_exporter_version }}/postgres_exporter-{{ postgresql_exporter_version }}.linux-amd64.tar.gz
    dest: /opt/
  become: true

- name: Create postgresql_exporter.service file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/postgresql_exporter.service.j2"
    dest: /etc/systemd/system/postgresql_exporter.service
    mode: '0644'
  become: true
  notify: "Restart postgresql_exporter"

- name: Enables postgresql_exporter daemon
  ansible.builtin.systemd:
    name: postgresql_exporter
    daemon_reload: true
    enabled: true
    state: started
  become: true

- name: "Create netbox service for postgresql_exporter"
  netbox.netbox.netbox_service:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      virtual_machine: "{{ inventory_hostname }}"
      name: postgresql_exporter
      port: "9116"
      protocol: TCP
    state: present
  delegate_to: localhost
  when:
    - "netbox_url is defined"
    - "netbox_token is defined"
    - "netbox_url is not none"
    - "netbox_token is not none"
